### PR TITLE
Use polymorphic urls.

### PR DESCRIPTION
**Pull request by tomkr**
This sets us up for better supporting multiple languages.
Add some translations.

### CODE REVIEW

**Comment by stefanroex** [comment]
:+1:

@jvdp This doesn't conflict with any upcoming changes, does it?

**Comment by jvdp** [comment]
I don't think so, should be fine.

@tomkr can you fix the merge artifacts? (Double `placeholder:`.)

**Comment by tomkr** [comment]
Whoops, some careless copy-pasting there. :sweat_smile: I'll get to work.

**Comment by jvdp** [comment]
:+1:

**Pull request merged**
